### ISSUE TITLE
Unit Test Case_1

### ISSUE THREAD

**Issue by farwabatool292** [farwabatool292/ST_A3#13]
Unit Testing:

Description:
 Unit Testing of the Store Management Section of the Admin side.

There are  further 3 subsections in this module.
1-Store
2-Store List
3-Create Store

These are separate pages  which appear separately on click on them. My assigned task is to perform the unit testing of 
Operation of these pages. And to check if on clicking these pages are working properly.

Test Automation:

Result of Test performed: Test Succesfull Pages are operating.

**Comment by JaveriaFAST** [comment]
Test Completed
